
#######################################
### Explore data generated by Sonia ###
#######################################



#########################
### Load Sonia's data ###
#########################
all_data <- readRDS("/home/sruiz/R/splicing_project/SplicingProject/Results/nonSexSpecificJunctions.rda")



##############################################################################################################
### Obtain the proportion of unique splice junctions that an individual expresses in all the brain tissues ###
##############################################################################################################

Proportion_personalised_splicing <- lapply(all_data$juncIDs_person_tissue,function(x){
  if(length(grep("Brain",names(x)))>5)
  {
    tmp_only_brain <- x[grep("Brain",names(x))]
    return(length(Reduce(intersect, tmp_only_brain))/length(Reduce(union, tmp_only_brain)))
  }
})

##
hist(unlist(Proportion_personalised_splicing)*100,breaks = 40, ylab="# Individuals",
     xlab=paste0("% of unique splice junctions share accross \n all the individual's brain tissues (mean : ",
                 round(mean(unlist(Proportion_personalised_splicing)*100),1),")"),
     main="Proportion personalised junction")


#########################################################
## Get the split reads frequencies across individuals ###
#########################################################


source("./functions.R")
freq.frontal <- getFreqTissue("Brain-FrontalCortex_BA9",countsDetection = 1)
mean.frontal <- getMeanJuncTissue("Brain-FrontalCortex_BA9",countsDetection = 1)
library(scales)


plot(head(freq.frontal,500000),log2(head(mean.frontal,500000)),
     xlab="% splice junction \n frequency across individuals",ylab = "log2(mean counts)",col=alpha("red", 0.01),
     main="Frequency VS mean counts in Frontal Cortex")


cor(head(freq.frontal,500000),log2(head(mean.frontal,500000)))

freq.wholeBlood <- getFreqTissue("WholeBlood",countsDetection = 1)
mean.wholeBlood <- getMeanJuncTissue("WholeBlood",countsDetection = 1)

plot(head(freq.wholeBlood,500000),log2(head(mean.wholeBlood,500000)),
     xlab="% splice junction \n frequency across individuals",ylab = "log2(mean counts)",col=alpha("red", 0.01),
     main="Frequency VS mean counts in Whole Blood")


cor(freq.wholeBlood,log2(mean.wholeBlood))


##########################################
## Get the unique junctions per sample ###
##########################################

all_data <- readRDS("/home/sruiz/R/splicing_project/SplicingProject/Results/nonSexSpecificJunctionsGreaterThan1.rda")
#all_data <- readRDS("/home/sruiz/R/splicing_project/SplicingProject/Results/nonSexSpecificJunctions_NumEvents_GT1.rda")
all_data$tissueIndividuals <- all_data$col_names

all_data$tissueIndividuals <- sapply(names(all_data$tissueIndividuals),function(tissue){
  print(tissue)
  tmp <- c()
  for(i in names(all_data$juncIDs_person_tissue))
  {
    
    if(any((tissue == names(all_data$juncIDs_person_tissue[[i]]))))
    {
      tmp <- c(tmp,i)
    }
  }
  return(tmp)
})

all_data$tissueIndividuals[[tissue]]

all_data$juncIDs_person_tissue$`GTEX-QMR6`$`Brain-Hippocampus`

all_data$juncIDs_person_tissue[[c("GTEX-QMR6")]][tissue]


lapply(all_data$juncIDs_person_tissue[all_data$tissueIndividuals[[tissue]][-i]],function()



all_data$tissueIndividuals[[tissue]]

head(all_data$juncIDs_person_tissue[all_data$tissueIndividuals[[tissue]]])[tmp_ind])

tissue <- "Brain-Hippocampus"
     sapply(names(all_data$tissueIndividuals),function(tissue){
       print(tissue)
       tmp <- list() 
       
       for(i in length(all_data$tissueIndividuals[[tissue]]))
       {
         
         tmp_ind <- c(all_data$tissueIndividuals[[tissue]][i],all_data$tissueIndividuals[[tissue]][-i])
         tmp[[all_data$tissueIndividuals[[tissue]][i]]] <- Reduce(setdiff,all_data$juncIDs_person_tissue[all_data$tissueIndividuals[[tissue]]][tmp_ind])
       }
       return(tmp)
     })
     
     
     all_data$juncIDs_person_tissue[[all_data$tissueIndividuals[[tissue]]]]
     map2
     
     
     all_data$juncIDs_person_tissue[[c("GTEX-QMR6","GTEX-OHPN")]]
     
     Reduce(union, all_data$samplesID_person)
     
     
     dat1 <- c("osa", "bli", "usd", "mnl")
     dat2 <- c("mnu", "erd", "usd", "mnl")
     dat3 <- c("ssu", "erd", "usd", "mnl")
     
     diffs <- Reduce(setdiff,list(A = dat1,B = dat2, C = dat3))
     
     
     #######################################
     ## Get the correlation variance-age ###
     #######################################
     
     
     all_data <- readRDS("/home/sruiz/R/splicing_project/SplicingProject/Results/nonSexSpecificJunctionsGreaterThan1.rda.rda")
     
     length(all_data$juncIDs_person_tissue$`GTEX-POMQ`)
     
     Proportion_personalised_splicing <- lapply(all_data$juncIDs_person_tissue,function(x){
       if(length(grep("Brain",names(x)))>5)
       {
         tmp_only_brain <- x[grep("Brain",names(x))]
         return(length(Reduce(intersect, tmp_only_brain))/length(Reduce(union, tmp_only_brain)))
       }
     })
     
     